export { default as Hero } from './Hero'
export { default as Stat } from './Stat'
export { default as Business } from './Business'
export { default as Billing } from './Billing'
export { default as CardDeal } from './CardDeal'
export { default as Feedback } from './Feedback'
export { default as Client } from './Client'
export { default as Cta } from './Cta'